import Head from "next/head";
import { NavItems } from "../../utils/home/navbar.json";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/router";

export default function () {
  const navItems = NavItems.map((item: any) => item);
  const [tab, setTab] = useState(0);
  const router = useRouter();

  const handleTab = (index: number) => {
    switch (index) {
      case 0: {
        setTab(index);
        window.scrollTo({
          top: 0,
          behavior: "smooth",
        });
        break;
      }
      case 1: {
        setTab(index);
        window.scrollTo({
          top: window.innerHeight > 1080 ? 1300 : 670,
          behavior: "smooth",
        });
        break;
      }
      case 2: {
        setTab(3);
        window.open("/contact", "_blank");
        break;
      }
    }
  };

  return (
    <>
      <Head>
        <title>Aeris, para colegios, profesores y estudiantes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sticky top-0 z-50 bg-white flex flex-row justify-between items-center h-[33px] px-[80px] py-[40px] shadow-sm ">
        <div className="flex flex-row">
          <Image
            src="/images/logoImage.png"
            alt="Logo"
            width={24}
            height={24}
            className="object-contain"
          />
          <a className="font-bold text-[24px] -tracking-[0.065em]">Aeris</a>
        </div>
        <div className="flex flex-row gap-20">
          {navItems.map((item: any, index: number) => (
            <>
              {tab === index ? (
                <a className="bg-[#72ADF3]/40 text-center rounded-[15px] py-1 cursor-pointer px-[15px]">
                  {item.title.toUpperCase()}
                </a>
              ) : (
                <a
                  className="cursor-pointer pt-1 hover:scale-110 hover:bg-[#72ADF3]/40 rounded-[15px] px-[15px] py-1 transition-all duration-300 ease-in-out"
                  onClick={() => handleTab(index)}
                >
                  {item.title.toUpperCase()}
                </a>
              )}
            </>
          ))}
        </div>
        <a
          className="w-[101px] h-[33px] bg-[#72ADF3]/40 text-black text-center text-base font-semibold rounded-[15px] pt-1 -tracking-[0.065em] cursor-pointer"
          onClick={() => router.push("/register")}
        >
          Regístrate
        </a>
      </div>
    </>
  );
}
